name: eden
description: "Eden"

version: 1.0.0+1

publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  multiple_localization: any
  eden_service:
    path: eden_service
  eden_uikit:
    path: eden_uikit
  eden_intl:
    path: eden_intl
  eden_logger:
    path: eden_logger
  eden_internet_connection_checker:
    path: eden_internet_connection_checker
  eden_utils:
    path: eden_utils
  eden_database:
    path: eden_database
  go_router: ^14.2.0
  meta: any
  provider: any
  # 国际化
  intl: ^0.19.0
  # 苹果主题icons
  cupertino_icons: ^1.0.8
  # 手机状态栏管理
  flutter_statusbarcolor_ns: ^0.5.0
  # 包信息获取
  package_info_plus: ^8.0.0
  # 状态管理
  flutter_riverpod: ^2.5.1
  riverpod: any
  riverpod_annotation: any
  freezed_annotation: ^2.4.1
  # 实体生成
  json_annotation: ^4.9.0
  # 网络请求
  dio: any
  dio_cookie_manager: ^3.1.1
  cookie_jar: any
  # 常用三方
  crypto: ^3.0.3
  convert: ^3.1.1
  path_provider: any
  path: any
  collection: any
  # web
  webview_flutter: ^4.8.0
  webview_cookie_manager: ^2.0.6
  url_launcher: ^6.3.0
  croppy: ^1.1.4
  image_compression_flutter: ^1.0.4
  image: any
  extended_list: any
  emoji_picker_flutter: any
  nine_grid_view: ^2.0.0
  vibration: any
  record: any
  video_player_media_kit: any
  video_player: any
  wechat_camera_picker: any
  jiffy: any
  flutter_blue_plus: ^1.32.8
  fl_chart: any
  blur: any
  mime: any
  network_info_plus: any
  connectivity_plus: any
  media_kit: any
  media_kit_video: any
  media_kit_libs_video: any
  web_socket_client: any
dependency_overrides:
  keyboard_height_plugin:
    git: https://github.com/q200892907/keyboard_height_plugin.git

# 开发中三方库引用
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  go_router_builder: any
  json_serializable: any
  icons_launcher: any
  freezed: any
  riverpod_generator: any
  riverpod_lint: any
  watcher: ^1.1.0
# flutter中相关配置
flutter:
  uses-material-design: true

  assets:
    - assets/config/
    - assets/www/
    # assets-generator-begin
    # assets/images/*
    # assets/*
    # assets-generator-end
