name: eden_uikit
description: "Eden uikit"
version: 1.0.0
homepage:

publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  eden_icons:
    path: ../eden_icons
  eden_internet_connection_checker:
    path: ../eden_internet_connection_checker
  eden_logger:
    path: ../eden_logger
  eden_utils:
    path: ../eden_utils
  eden_intl:
    path: ../eden_intl
  http: any
  shared_preferences: any
  flutter_screenutil: ^5.9.3 #Apache-2.0
  device_info_plus: ^10.1.0 #BSD-3-Clause
  auto_orientation: ^2.3.1 #Apache-2.0
  oktoast: ^3.4.0 #Apache-2.0
  adaptive_theme: ^3.6.0 #Apache-2.0
  theme_tailor_annotation: ^3.0.1
  textstyle_extensions: ^2.0.0-nullsafety #MIT
  cached_network_image: ^3.3.1 #MIT
  flutter_cache_manager: ^3.3.2 #MIT
  back_button_interceptor: ^7.0.3 #BSD-2-Clause
  flutter_spinkit: ^5.2.1 #MIT
  pull_to_refresh: ^2.0.0 #MIT
  collection: ^1.18.0 #BSD-3-Clause
  # 网络状态判断
  connectivity_plus: any
  riverpod: any
  flutter_riverpod: any
  freezed_annotation: any
  badges: ^3.1.2
  riverpod_context: ^0.3.0
  auto_size_text: ^3.0.0
  path_drawing: any
  extended_wrap: ^0.1.5
  extended_text: ^13.0.2
  animated_toggle_switch: ^0.8.2
  keframe: ^3.0.0
  romanice: ^2.0.0
  photo_view: ^0.15.0
  smooth_page_indicator: ^1.1.0
  image_gallery_saver: any
  extended_image: any
  convex_bottom_bar: ^3.2.0
  azlistview_plus: ^3.0.0
  visibility_detector: ^0.4.0+2
  crypto: any
  percent_indicator: ^4.2.3
  flutter_slidable: any
  extended_text_field: ^15.0.0
  flutter_keyboard_visibility: any
  keyboard_height_plugin: any
  card_swiper: any
  flutter_svg: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  json_serializable: any
  theme_tailor: any
  freezed: any
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
