name: eden_logger
description: eden logger
version: 1.0.0
homepage:

publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # 信息打印
  logger: any
  intl: any
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:


